#!/bin/bash

ASTERISKDIR=/var/spool/recording
VIDEOFILE=$ASTERISKDIR/$1.mkv
AUDIOFILE=$ASTERISKDIR/$2.mp3
TEMPFILE=$ASTERISKDIR/temp$3.mp4
VIDEORESULT=/var/spool/recording/$3.mp4
DESTSERVER=$4
DIRDESTSERVER=/home/webrtc/videocall/$5
PASSWORD=INIPASSWORD

ffmpeg -i $VIDEOFILE -vcodec libx264 -crf 30 $TEMPFILE

ffmpeg -i $TEMPFILE -i $AUDIOFILE -c:v copy -c:a aac -strict experimental -map 0:v:0 -map 1:a:0 $VIDEORESULT

if [ -f "$VIDEORESULT" ]; then
	echo "Combine Successfull"
	echo "Delete $VIDEOFILE $AUDIOFILE $TEMPFILE"
	rm -rf $VIDEOFILE $AUDIOFILE $TEMPFILE
	sshpass -p $PASSWORD scp $VIDEORESULT $DESTSERVER:$DIRDESTSERVER
	rm -rf $VIDEORESULT
else
	echo "Failed create combined video"
	echo "Delete $TEMPFILE"
	rm -rf $TEMPFILE
fi

