#!/bin/bash

ASTERISKDIR=/var/spool/recording
LOGFILE=/var/spool/recording/log/$3.log
VIDEOFILE=$ASTERISKDIR/$1.mkv
AUDIOFILE=$ASTERISKDIR/$2.mp3
TEMPFILE=$ASTERISKDIR/temp$3.mp4
VIDEORESULT=/var/spool/recording/$3.mp4
DESTSERVER=$4
DIRDESTSERVER=/data/webrtc/videocall/$5
PASSWORD=P@ssw0rd

echo "convert video codec" >> $LOGFILE
ffmpeg -i $VIDEOFILE -vcodec libx264 -crf 30 $TEMPFILE 2>> $LOGFILE
echo "combine audio and video" >> $LOGFILE
ffmpeg -i $TEMPFILE -i $AUDIOFILE -c:v copy -c:a aac -strict experimental -map 0:v:0 -map 1:a:0 $VIDEORESULT 2>> $LOGFILE

if [ -f "$VIDEORESULT" ]; then
	echo "Combine successfull" >> $LOGFILE
	echo "Delete $VIDEOFILE $AUDIOFILE $TEMPFILE" >> $LOGFILE
	rm -rf $VIDEOFILE $AUDIOFILE $TEMPFILE >> $LOGFILE
	sshpass -p $PASSWORD scp $VIDEORESULT $DESTSERVER:$DIRDESTSERVER >> $LOGFILE
	rm -rf $VIDEORESULT >> $LOGFILE
else
	echo "Failed create combined video" >> $LOGFILE
	echo "Delete $TEMPFILE" >> $LOGFILE
	rm -rf $TEMPFILE >> $LOGFILE
fi

